/* App core: state, router, modal, toast, theme, login, dashboard, sales, customers, settings */
let CU=null,S={page:'dashboard',pp:1,q:'',cat:'',st:'',sort:'name',cart:[],disc:0};
const $=(s,r=document)=>r.querySelector(s),st=()=>DB.get('settings');
const money=n=>st().currency+' '+Math.round(n).toLocaleString();
const fdate=d=>new Date(d).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stockStatus=p=>p.stock<=0?'OUT OF STOCK':p.stock<=p.min/2?'CRITICAL':p.stock<=p.min?'LOW STOCK':'IN STOCK';
const badge=s=>`<span class="badge ${({'OUT OF STOCK':'danger',CRITICAL:'warn','LOW STOCK':'warn2','IN STOCK':'ok',Paid:'ok',Active:'ok'})[s]||'muted'}">${s}</span>`;
const lowList=()=>DB.get('products').filter(p=>p.stock<=p.min).sort((a,b)=>a.stock-b.stock);
function toast(m,t='success'){const e=document.createElement('div');e.className='toast '+t;e.textContent=m;$('#toasts').append(e);setTimeout(()=>e.remove(),3200)}
function modal(t,b,f=''){const m=$('#modal');m.hidden=false;m.innerHTML=`<div class="dlg" role="dialog" aria-modal="true" aria-label="${esc(t)}"><h3>${t}<button class="x" onclick="closeModal()" aria-label="Close">×</button></h3><div class="mb">${b}</div><div class="mf">${f}</div></div>`;const i=m.querySelector('input,select,button.btn');i&&i.focus()}
const closeModal=()=>{$('#modal').hidden=true};
document.addEventListener('keydown',e=>{if(e.key=='Escape')closeModal()});
function notify(m){const n=DB.get('notes',[]);n.unshift({m,t:Date.now(),read:false});DB.set('notes',n.slice(0,20));badgeUpd()}
function badgeUpd(){const u=DB.get('notes',[]).filter(n=>!n.read).length;$('#badge').textContent=u||''}
const NAV=[['dashboard','▦','Dashboard',pDashboard],['pos','🛒','POS / Sales',pPos],['products','📦','Products',pProducts],['lowstock','⚠️','Low Stock',pLow],['sales','🧾','Sales History',pSales],['customers','👥','Customers',pCustomers],['employees','🪪','Employees / Users',pEmployees],['reports','📊','Reports',pReports],['settings','⚙️','Settings',pSettings]];
function buildNav(){$('#nav').innerHTML=NAV.filter(n=>can(n[0])).map(n=>`<button data-p="${n[0]}" class="${S.page==n[0]?'on':''}" onclick="go('${n[0]}')"><span>${n[1]}</span>${n[2]}</button>`).join('')}
function go(p){S.page=p;const n=NAV.find(x=>x[0]==p);$('#main').innerHTML=can(p)?n[3]():'<div class="card empty"><h2>Access Restricted</h2><p>You don\'t have permission to access this section.</p></div>';buildNav();$('#side').classList.remove('open');scrollTo(0,0)}
const rerender=()=>go(S.page);
function pDashboard(){const sales=DB.get('sales'),D=k=>new Date(Date.now()-k*864e5).toDateString(),day=k=>sales.filter(s=>new Date(s.date).toDateString()==D(k)),sum=a=>a.reduce((t,s)=>t+s.total,0),ch=(a,b)=>b?((a-b)/b*100):0,
 ts=day(0),ys=day(1),cs=ch(sum(ts),sum(ys)),co=ch(ts.length,ys.length),pr=DB.get('products'),ar=v=>`<span class="${v>=0?'up':'dn'}">${v>=0?'▲ +':'▼ '}${v.toFixed(1)}% from yesterday</span>`;
 const cards=[['💰',"Today's Sales",money(sum(ts)),ar(cs)],['🧾',"Today's Orders",ts.length,ar(co)],['📦','Total Products',pr.length,`<span class="mu sm">${new Set(pr.map(p=>p.cat)).size} categories</span>`],['⚠️','Low Stock Items',lowList().length,'<span class="dn">Needs restock</span>'],['👥','Total Customers',DB.get('customers').length,'<span class="mu sm">Registered</span>'],['🪪','Total Employees',DB.get('employees').length,'<span class="mu sm">Active staff</span>']];
 const days=[6,5,4,3,2,1,0].map(k=>({l:new Date(Date.now()-k*864e5).toLocaleDateString('en-GB',{weekday:'short'}),v:sum(day(k)),o:day(k).length})),mx=Math.max(1,...days.map(d=>d.v));
 return head('Dashboard',`Welcome back, ${esc(CU.name)}`)+`<div class="stats">${cards.map(c=>`<div class="card stat"><div class="ic">${c[0]}</div><div><b>${c[2]}</b>${c[1]}<br>${c[3]}</div></div>`).join('')}</div>
 <div class="two"><div class="card"><h3 style="margin-top:0">Sales Overview · Last 7 days</h3><div class="chart">${days.map(d=>`<div class="bar" title="${money(d.v)} · ${d.o} orders"><span>${d.o}</span><i style="height:${d.v/mx*80}%"></i>${d.l}</div>`).join('')}</div></div>
 <div class="card"><h3 style="margin-top:0">Low Stock Products</h3>${lowList().slice(0,5).map(p=>`<div class="cl"><span>${esc(p.name)}<br><span class="sm mu">${p.stock} / min ${p.min}</span></span>${badge(stockStatus(p))}</div>`).join('')}<button class="btn sm" style="margin-top:8px" onclick="go('lowstock')">View all</button></div></div>
 <div class="card"><h3 style="margin-top:0">Recent Sales</h3>${salesTable(sales.slice(0,6))}</div>`}
function salesTable(l){if(!l.length)return '<div class="empty">No sales found</div>';return `<table class="tbl"><thead><tr><th>Invoice #</th><th>Customer</th><th>Items</th><th>Amount</th><th>Payment</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>${l.map(s=>`<tr><td data-label="Invoice">${s.id}</td><td data-label="Customer">${esc(s.customer)}</td><td data-label="Items">${s.items.length}</td><td data-label="Amount">${money(s.total)}</td><td data-label="Payment">${s.pay}</td><td data-label="Date">${fdate(s.date)}</td><td data-label="Status">${badge(s.status)}</td><td data-label="Action"><button class="btn sm" onclick="viewSale('${s.id}')">View</button><button class="btn sm" onclick="printDlg('sale','${s.id}')">Print</button></td></tr>`).join('')}</tbody></table>`}
function viewSale(id){const s=DB.get('sales').find(x=>x.id==id);modal('Sale '+s.id,`<p>${esc(s.customer)} · ${fdate(s.date)} · ${s.pay}</p>${s.items.map(i=>`<div class="cl"><span>${esc(i.name)} × ${i.qty}</span><b>${money(i.price*i.qty)}</b></div>`).join('')}<div class="tr g"><span>Total</span><span>${money(s.total)}</span></div>`,`<button class="btn" onclick="printDlg('sale','${id}')">Print</button><button class="btn pri" onclick="closeModal()">Close</button>`)}
const salesFiltered=()=>DB.get('sales').filter(s=>(!S.sq||s.id.toLowerCase().includes(S.sq.toLowerCase())||s.customer.toLowerCase().includes(S.sq.toLowerCase()))&&(!S.sp||s.pay==S.sp));
function pSales(){return head('Sales History','All completed invoices','<button class="btn" onclick="csv(\'sales\')">Export</button>')+`<div class="card"><div class="tools"><input aria-label="Search invoice or customer" placeholder="Search invoice or customer" oninput="S.sq=this.value;$('#stbl').innerHTML=salesTable(salesFiltered())"><select aria-label="Payment" onchange="S.sp=this.value;$('#stbl').innerHTML=salesTable(salesFiltered())"><option value="">All payments</option><option>Cash</option><option>Card</option><option>Bank Transfer</option></select></div><div id="stbl">${salesTable(salesFiltered())}</div></div>`}
function pCustomers(){const s=DB.get('sales');return head('Customers','Your customer directory')+`<div class="card"><table class="tbl"><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Orders</th><th>Total Spent</th></tr></thead><tbody>${DB.get('customers').map(c=>{const o=s.filter(x=>x.customer==c.name);return `<tr><td data-label="Name"><b>${esc(c.name)}</b></td><td data-label="Phone">${c.phone}</td><td data-label="Email">${c.email}</td><td data-label="Orders">${o.length}</td><td data-label="Spent">${money(o.reduce((t,x)=>t+x.total,0))}</td></tr>`}).join('')}</tbody></table></div>`}
function pSettings(){const s=st(),f=(k,l,t='text')=>`<label>${l}<input id="s_${k}" type="${t}" value="${esc(s[k])}"></label>`;
 return head('Settings','Shop, tax, currency and print defaults')+`<div class="card"><div class="grid2">${f('shop','Shop Name')}${f('address','Address')}${f('phone','Phone')}${f('email','Email')}${f('currency','Currency Symbol')}${f('tax','Tax %','number')}${f('thank','Thank-you message')}<label>Default Paper<select id="s_paper">${[['t58','Thermal 58mm'],['t80','Thermal 80mm'],['a4','A4']].map(o=>`<option value="${o[0]}" ${s.paper==o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></label><label class="chk"><input type="checkbox" id="s_bg" ${s.bg?'checked':''}> Print background on A4 by default</label></div><div class="acts" style="margin-top:14px">${can('settings','edit')?'<button class="btn pri" onclick="saveSettings()">Save Settings</button><button class="btn dan" onclick="resetDlg()">Reset Demo Data</button>':''}</div><p class="mu sm">Storage: browser localStorage · ${DB.get('products').length} products · ${DB.get('sales').length} sales</p></div>`}
function saveSettings(){const t=parseFloat($('#s_tax').value);if(isNaN(t)||t<0||t>100)return toast('Tax must be between 0 and 100','error');
 DB.set('settings',{...st(),shop:$('#s_shop').value,address:$('#s_address').value,phone:$('#s_phone').value,email:$('#s_email').value,currency:$('#s_currency').value||'Rs.',tax:t,thank:$('#s_thank').value,paper:$('#s_paper').value,bg:$('#s_bg').checked});$('#shopName').textContent=st().shop;toast('Settings saved')}
const resetDlg=()=>modal('Reset Demo Data?','<p>Resetting demo data will remove all locally stored changes.</p>','<button class="btn" onclick="closeModal()">Cancel</button><button class="btn dan" onclick="DB.reset();seedData();location.reload()">Reset</button>');
function profile(){modal('My Profile',`<p><b>${esc(CU.name)}</b><br>${esc(CU.email)} · Role: ${CU.role} · ${CU.perms.length} permissions</p><div class="sm">${CU.perms.join(', ')}</div><label>New password<input id="np" type="password"></label>`,'<button class="btn" onclick="closeModal()">Close</button><button class="btn pri" onclick="chgPw()">Change Password</button>')}
function chgPw(){const p=$('#np').value;if(p.length<6)return toast('Min 6 characters','error');const L=DB.get('employees');L.find(e=>e.id==CU.id).pass=p;DB.set('employees',L);closeModal();toast('Password updated')}
function bell(){const n=DB.get('notes',[]);modal('Notifications',n.length?n.map(x=>`<div class="cl"><span>${esc(x.m)}</span><span class="sm mu">${new Date(x.t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div>`).join(''):'<div class="empty">No notifications</div>','<button class="btn" onclick="closeModal()">Close</button>');DB.set('notes',n.map(x=>({...x,read:true})));badgeUpd()}
function enter(u){CU=u;$('#login').hidden=true;$('#app').hidden=false;$('#shopName').textContent=st().shop;$('#meName').textContent=u.name;$('#meRole').textContent=u.role;$('#date').textContent=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short',year:'numeric'});
 const c=lowList().filter(p=>stockStatus(p)!='LOW STOCK').length;if(c&&!DB.get('notes',[]).length)notify(`${c} products are critically low on stock.`);badgeUpd();S.page=can('dashboard')?'dashboard':'products';go(S.page)}
$('#lf').onsubmit=e=>{e.preventDefault();const u=DB.get('employees').find(x=>x.email==$('#le').value.trim()&&x.pass==$('#lp').value&&x.status=='Active');if(!u){$('#lerr').textContent='Invalid email or password';return}
 const L=DB.get('employees');L.find(x=>x.id==u.id).last=new Date().toISOString();DB.set('employees',L);$('#lr').checked?DB.set('session',u.id):DB.set('session',null);enter(u)};
$('#logout').onclick=()=>{DB.set('session',null);location.reload()};
$('#theme').onclick=()=>{const d=document.documentElement.dataset.theme=='dark'?'light':'dark';document.documentElement.dataset.theme=d;DB.set('theme',d)};
$('#burger').onclick=()=>$('#side').classList.toggle('open');$('#bell').onclick=bell;
$('#gsearch').onkeydown=e=>{if(e.key=='Enter'&&can('products')){S.q=e.target.value;S.pp=1;go('products')}};
document.documentElement.dataset.theme=DB.get('theme','light');$('#lshop').textContent=st().shop;
const sid=DB.get('session');if(sid){const u=DB.get('employees').find(x=>x.id==sid);u&&enter(u)}
