/* Employees & access control */
function empRows(){const q=(S.eq||'').toLowerCase();return DB.get('employees').filter(e=>(!q||e.name.toLowerCase().includes(q))&&(!S.er||e.role==S.er)&&(!S.es||e.status==S.es))}
function empTable(){const l=empRows();if(!l.length)return '<div class="empty">No employees found</div>';
 return `<table class="tbl"><thead><tr><th>Employee</th><th>Email</th><th>Phone</th><th>Role</th><th>Department</th><th>Access</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>${l.map(e=>`<tr><td data-label="Employee"><b>${esc(e.name)}</b><br><span class="sm mu">${e.eid}</span></td><td data-label="Email">${esc(e.email)}</td><td data-label="Phone">${e.phone}</td><td data-label="Role">${e.role}</td><td data-label="Dept">${esc(e.dept)}</td><td data-label="Access">${e.perms.length} permissions</td><td data-label="Status">${badge(e.status)}</td><td data-label="Last login">${fdate(e.last)}</td><td data-label="Actions" class="act">${can('employees','edit')?`<button class="btn sm" onclick="empForm('${e.id}')">Edit</button>`:''}</td></tr>`).join('')}</tbody></table>`}
const updEmp=()=>{$('#etbl').innerHTML=empTable()};
function pEmployees(){return head('Employees & Access Management','Manage staff and what they can do',can('employees','create')?'<button class="btn pri" onclick="empForm()">+ Add Employee</button>':'')+
 `<div class="card"><div class="tools"><input aria-label="Search" placeholder="Search name" oninput="S.eq=this.value;updEmp()"><select aria-label="Role" onchange="S.er=this.value;updEmp()"><option value="">All roles</option>${Object.keys(PRESETS).map(r=>`<option>${r}</option>`).join('')}</select><select aria-label="Status" onchange="S.es=this.value;updEmp()"><option value="">All status</option><option>Active</option><option>Inactive</option></select></div><div id="etbl">${empTable()}</div></div>`}
function permGrid(perms){return `<table class="permt"><tr><th>Module</th>${ACTS.map(a=>`<th>${a}</th>`).join('')}</tr>${MODS.map(m=>`<tr><td>${MODLABEL[m]}</td>${ACTS.map(a=>`<td><input type="checkbox" class="pmc" value="${m}.${a}" aria-label="${MODLABEL[m]} ${a}" ${perms.includes(m+'.'+a)?'checked':''}></td>`).join('')}</tr>`).join('')}</table>`}
function applyPreset(){const p=PRESETS[$('#e_role').value];document.querySelectorAll('.pmc').forEach(c=>c.checked=p.includes(c.value))}
function empForm(id){const e=id?DB.get('employees').find(x=>x.id==id):{name:'',email:'',phone:'',dept:'Sales',role:'cashier',eid:'EMP-'+(100+DB.get('employees').length),status:'Active',perms:PRESETS.cashier};
 const f=(k,l,t='text',x='')=>`<label>${l}<input id="e_${k}" type="${t}" value="${esc(e[k]??'')}" ${x}></label>`;
 modal(id?'Edit Employee':'Add Employee',`<div class="grid2">${f('name','Full Name *')}${f('email','Email *','email')}${f('phone','Phone')}${f('eid','Employee ID')}${f('dept','Department')}<label>Role / Access preset<select id="e_role" onchange="applyPreset()">${Object.keys(PRESETS).map(r=>`<option ${e.role==r?'selected':''}>${r}</option>`).join('')}</select></label>
 <label>Password ${id?'(leave blank to keep)':'*'}<input id="e_pass" type="password"></label><label>Confirm Password<input id="e_pass2" type="password"></label><label>Status<select id="e_status"><option ${e.status=='Active'?'selected':''}>Active</option><option ${e.status=='Inactive'?'selected':''}>Inactive</option></select></label></div><b>Access Control</b>${permGrid(e.perms)}<div id="ferr" class="err"></div>`,
 `<button class="btn" onclick="closeModal()">Cancel</button><button class="btn pri" onclick="saveEmp(${id?`'${id}'`:'null'})">Save Employee</button>`)}
function saveEmp(id){const v=k=>$('#e_'+k).value.trim(),L=DB.get('employees'),er=[];
 if(!v('name'))er.push('Full name is required');if(!/^\S+@\S+\.\S+$/.test(v('email')))er.push('Valid email is required');else if(L.some(x=>x.email==v('email')&&x.id!=id))er.push('Email already in use');
 if(!id&&v('pass').length<6)er.push('Password must be at least 6 characters');if(v('pass')!=v('pass2'))er.push('Passwords do not match');
 if(er.length){$('#ferr').innerHTML=er.join('<br>');return}
 const perms=[...document.querySelectorAll('.pmc:checked')].map(c=>c.value),d={name:v('name'),email:v('email'),phone:v('phone'),eid:v('eid'),dept:v('dept'),role:v('role'),status:v('status'),perms};
 if(id){const e=L.find(x=>x.id==id);Object.assign(e,d);if(v('pass'))e.pass=v('pass');if(CU.id==id)CU=e;notify(`Employee ${d.name} updated`)}else{L.push({id:'e'+Date.now(),pass:v('pass'),last:new Date().toISOString(),...d});notify(`Employee ${d.name} was added`)}
 DB.set('employees',L);closeModal();toast('Employee saved');rerender();buildNav()}
