const CAT_ICON={Dairy:'🥛',Bakery:'🍞',Grocery:'🌾',Beverages:'🥤',Snacks:'🍪','Personal Care':'🧴',Household:'🧽'};
const ico=p=>CAT_ICON[p.cat]||'📦';
const head=(t,sub,b='')=>`<div class="ph"><div><div class="crumb">Home / ${t}</div><h1>${t}</h1><p class="mu">${sub}</p></div><div class="acts">${b}</div></div>`;
function filteredProducts(){let l=DB.get('products');const q=S.q.toLowerCase();
 if(q)l=l.filter(p=>[p.name,p.sku,p.cat].join(' ').toLowerCase().includes(q));
 if(S.cat)l=l.filter(p=>p.cat==S.cat);if(S.st)l=l.filter(p=>stockStatus(p)==S.st);
 const k=S.sort;return l.sort((a,b)=>k=='name'?a.name.localeCompare(b.name):k=='price'?a.price-b.price:k=='stock'?a.stock-b.stock:new Date(b.created)-new Date(a.created))}
function actions(p){return `<button class="btn sm" onclick="viewProd('${p.id}')">View</button>`+(can('products','edit')?`<button class="btn sm" onclick="prodForm('${p.id}')">Edit</button>`:'')+(can('products','delete')?`<button class="btn sm dan" onclick="delProd('${p.id}')">Delete</button>`:'')}
function prodTable(){const l=filteredProducts(),pages=Math.max(1,Math.ceil(l.length/10));S.pp=Math.min(S.pp,pages);const rows=l.slice((S.pp-1)*10,S.pp*10);
 if(!l.length)return '<div class="empty">No products match your filters.</div>';
 return `<table class="tbl"><thead><tr><th></th><th>Product</th><th>SKU</th><th>Category</th><th>Purchase</th><th>Sale</th><th>Stock</th><th>Min</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>${rows.map(p=>`<tr><td data-label="">${ico(p)}</td><td data-label="Product"><b>${esc(p.name)}</b></td><td data-label="SKU">${esc(p.sku)}</td><td data-label="Category">${esc(p.cat)}</td><td data-label="Purchase">${money(p.buy)}</td><td data-label="Sale">${money(p.price)}</td><td data-label="Stock">${p.stock}</td><td data-label="Min">${p.min}</td><td data-label="Status">${badge(stockStatus(p))}</td><td data-label="Created">${fdate(p.created)}</td><td data-label="Actions" class="act">${actions(p)}</td></tr>`).join('')}</tbody></table><div class="pg"><button class="btn" ${S.pp<2?'disabled':''} onclick="S.pp--;updTable()">‹ Prev</button>Page ${S.pp} / ${pages}<button class="btn" ${S.pp>=pages?'disabled':''} onclick="S.pp++;updTable()">Next ›</button></div>`}
const updTable=()=>{$('#tbl').innerHTML=prodTable()};
function pProducts(){const cats=[...new Set(DB.get('products').map(p=>p.cat))];
 return head('Products','Manage your inventory and products',(can('products','create')?'<button class="btn pri" onclick="prodForm()">+ Add Product</button>':'')+'<button class="btn" onclick="csv(\'products\')">Export</button><button class="btn" onclick="printDlg(\'lowstock\')">Print</button>')+
 `<div class="card"><div class="tools"><input aria-label="Search" placeholder="Search name, SKU, category" value="${esc(S.q)}" oninput="S.q=this.value;S.pp=1;updTable()"><select aria-label="Category" onchange="S.cat=this.value;S.pp=1;updTable()"><option value="">All categories</option>${cats.map(c=>`<option ${S.cat==c?'selected':''}>${c}</option>`).join('')}</select><select aria-label="Stock status" onchange="S.st=this.value;S.pp=1;updTable()"><option value="">All stock</option>${['IN STOCK','LOW STOCK','CRITICAL','OUT OF STOCK'].map(c=>`<option ${S.st==c?'selected':''}>${c}</option>`).join('')}</select><select aria-label="Sort" onchange="S.sort=this.value;updTable()">${[['name','Sort: Name'],['price','Price'],['stock','Stock'],['date','Newest']].map(o=>`<option value="${o[0]}" ${S.sort==o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></div><div id="tbl">${prodTable()}</div></div>`}
function prodForm(id){const p=id?DB.get('products').find(x=>x.id==id):{name:'',sku:'',cat:'Grocery',brand:'',unit:'pcs',buy:'',price:'',disc:0,stock:'',min:10,supplier:'',desc:'',status:'Active'};
 const f=(k,l,t='text')=>`<label>${l}<input id="f_${k}" type="${t}" value="${esc(p[k])}" ${t=='number'?'step="any" min="0"':''}></label>`;
 modal(id?'Edit Product':'Add Product',`<div class="grid2">${f('name','Product Name *')}${f('sku','SKU / Barcode *')}${f('cat','Category *')}${f('brand','Brand')}${f('unit','Unit')}${f('buy','Purchase Price *','number')}${f('price','Sale Price *','number')}${f('disc','Discount %','number')}${f('stock','Current Stock *','number')}${f('min','Minimum Stock *','number')}${f('supplier','Supplier')}<label>Status<select id="f_status"><option>Active</option><option>Inactive</option></select></label></div><label>Description<textarea id="f_desc">${esc(p.desc)}</textarea></label>${id?`<p class="mu">Last updated: ${fdate(p.updated)}</p>`:''}<div id="ferr" class="err"></div>`,
 `<button class="btn" onclick="closeModal()">Cancel</button><button class="btn pri" onclick="saveProd(${id?`'${id}'`:'null'})">Save Product</button>`);$('#f_status').value=p.status}
function saveProd(id){const v=k=>$('#f_'+k).value.trim(),n=k=>parseFloat(v(k)),L=DB.get('products'),e=[];
 if(!v('name'))e.push('Product name is required');if(!v('sku'))e.push('SKU is required');else if(L.some(x=>x.sku==v('sku')&&x.id!=id))e.push('SKU already exists');if(!v('cat'))e.push('Category is required');
 [['buy','Purchase price'],['price','Sale price'],['stock','Current stock'],['min','Minimum stock']].forEach(([k,l])=>{if(isNaN(n(k))||n(k)<0)e.push(l+' must be a valid number (0 or more)')});
 if(!e.length&&n('price')<n('buy'))e.push('Sale price cannot be lower than purchase price');
 if(!e.length&&(!Number.isInteger(n('stock'))||!Number.isInteger(n('min'))))e.push('Stock values must be whole numbers');
 if(e.length){$('#ferr').innerHTML=e.join('<br>');return}
 const now=new Date().toISOString(),d={name:v('name'),sku:v('sku'),cat:v('cat'),brand:v('brand'),unit:v('unit')||'pcs',buy:n('buy'),price:n('price'),disc:n('disc')||0,stock:n('stock'),min:n('min'),supplier:v('supplier'),desc:v('desc'),status:v('status'),updated:now};
 if(id){Object.assign(L.find(x=>x.id==id),d);notify(`Product ${d.name} updated`)}else{L.unshift({id:'p'+Date.now(),created:now,...d});notify(`Product ${d.name} added`)}
 DB.set('products',L);closeModal();toast(id?'Product updated successfully':'Product added successfully');rerender()}
function viewProd(id){const p=DB.get('products').find(x=>x.id==id);modal(p.name,`<div class="grid2">${[['SKU',p.sku],['Category',p.cat],['Brand',p.brand||'-'],['Supplier',p.supplier||'-'],['Purchase',money(p.buy)],['Sale',money(p.price)],['Stock',p.stock+' '+p.unit],['Minimum',p.min],['Status',stockStatus(p)],['Updated',fdate(p.updated)]].map(x=>`<div><span class="mu sm">${x[0]}</span><br><b>${esc(x[1])}</b></div>`).join('')}</div>`,'<button class="btn" onclick="closeModal()">Close</button>')}
function delProd(id){if(!can('products','delete'))return;modal('Delete Product?','<p>Are you sure you want to delete this product? This action cannot be undone.</p>',`<button class="btn" onclick="closeModal()">Cancel</button><button class="btn dan" onclick="doDel('${id}')">Delete Product</button>`)}
function doDel(id){DB.set('products',DB.get('products').filter(p=>p.id!=id));closeModal();toast('Product deleted','warning');rerender()}
function pLow(){const l=lowList(),c=s=>l.filter(p=>stockStatus(p)==s).length;
 return head('Low Stock','Products at or below their reorder level','<button class="btn pri" onclick="printDlg(\'lowstock\')">🖨 Print Low Stock</button>')+
 `<div class="stats">${[['🚨','Critical Stock',c('CRITICAL')],['⚠️','Low Stock',c('LOW STOCK')],['⛔','Out of Stock',c('OUT OF STOCK')]].map(x=>`<div class="card stat"><div class="ic">${x[0]}</div><div><b>${x[2]}</b>${x[1]}</div></div>`).join('')}</div>
 <div class="card">${l.length?`<table class="tbl"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Stock</th><th>Min</th><th>Supplier</th><th>Status</th><th>Action</th></tr></thead><tbody>${l.map(p=>`<tr><td data-label="Product"><b>${esc(p.name)}</b></td><td data-label="SKU">${p.sku}</td><td data-label="Category">${p.cat}</td><td data-label="Stock">${p.stock}</td><td data-label="Min">${p.min}</td><td data-label="Supplier">${esc(p.supplier)}</td><td data-label="Status">${badge(stockStatus(p))}</td><td data-label="Action" class="act">${actions(p)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">All products are well stocked 🎉</div>'}</div>`}
